# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ShakeList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShakeList
  
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  
  pod 'Firebase/Functions'
end
